# Generated by Django 6.0.3 on 2026-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinput',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
